# Generated by Django 3.2.4 on 2021-07-20 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='photo',
            field=models.ImageField(default=' ', upload_to=''),
            preserve_default=False,
        ),
    ]
